yarnPath: .yarn/releases/yarn-3.6.3.cjs

# `nodeLinker` is set to `node-modules` because if default `pnp` is used, 
# then editors cannot detect dependency and neither can support auto-completion
nodeLinker: node-modules